language: java
jdk:
- openjdk8
dist: bionic
before_install:
- openssl aes-256-cbc -K $encrypted_8f2a81d544cc_key -iv $encrypted_8f2a81d544cc_iv -in travis/pubring.gpg.enc -out travis/pubring.gpg -d
- openssl aes-256-cbc -K $encrypted_5c292d804727_key -iv $encrypted_5c292d804727_iv -in travis/secring.gpg.enc -out travis/secring.gpg -d
script:
- mvn verify
after_success:
- mvn coveralls:report
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && mvn deploy --settings travis/settings.xml -DskipTests=true -Possrh -Prelease
cache:
  directories:
  - "~/.m2"
branches:
  only:
  - master
  - "/^bullet-dsl-[0-9]+\\.[0-9]+\\.[0-9]+/"
env:
  global:
  - GPG_EXECUTABLE=gpg
  - secure: yC3uuogStcP0MaxO+wZJGEU7AKRHnBxQl9CLBD1tkd2+WuWtqbA2nKzCKffNQKemt5xK3LEiDVoWkKOQMXz3D+7JTanIhnxdk3JGvY0fSJ+Z5EPLx8AXn2Zc/YgrmWPm3hVI5UJ/nssPrFMmD0YR/F2PPmYLbZzDc1uxWFWO9pa5fFvJ3yKTY2D8iY8SLVBkm1/c4RwxEWdCdsd177DKSiUWX1YrfKOgqmlBYSzIJ2009tBgQPo+6I94R0L8+u4mxBLhI59s7+s38erUKHYwyCboa9y+2ETbTf9EC/ZRSutOlyK70nHoNI/sWJ4KgT/E6kW81cvZ9cSGxTxSevPRn8PbYmXX6duwrxQxNPkEjG7nwE8ksl8S5MljXHeG0QokFMoNS7B4dvav99ig3AnZXO9gNuEkVXvPcpOcP+fV7oxRiu+5RP80YazZVhAfkIhMpP9fmyLUHapSFr1m7Okg1TtXMTGyv+YDZUhMgrkYlwXZWGhfmPDU0rxEoeiTQ4gAtg2QFZusaaQBhpsRQCi++TL9YOFBM7+NFR7mB0jAZYrZI9/A4Ol0oUnyPMnlzHvFxKAHq4LkS4xBw2UdG60sXjAB09bX1UGXt2d4e360eoKzNdncA2gihen3oocGN+C8MgtM878qqtV4snrIgU723Fvx6VjjCFuo4S2nN+P6U2s=
  - secure: kyeZjfrgU0YinP6k3Cbsgmd6Za1FFjapJaPLXx3lZ9fvPfWASr+ZIZ7G+QrvFXZzWRmT/HykhCH3UFYmrqDyzsns937ZVH2KHlBVHRiTlABJRHrhnUZIFeG4zqsder2hwKxQXnGz3cw3QPQ5tB2Pctstu1Y99mDNJmuoYlvHfNgLgsqvbqKfLtQpNqCB0C6a9IPhH6zO4vT+7rh59JCP6JOGz5QgdZ1CEnrt3JqLWLRFXo+hc0Rwet6ppshP17tx50GnoN8rbYvLvnznApmIyeAZ2HM+oNcWY+kAnQcErjsXY5IMXQaB97cLeS4EhG5tLgwUYJdFhtMvYYVxnEDxylUbSohHrzSBzju6501y26ImWcKWwFDlWO1XQyFx/Lz5Va9bpoPPTnogdzkF1UuesDpi8B3VmoU17AmO3Y7HMdJDIvBy+y8Ne76wI9mONpdqwp66Rs6b5egR8+Lokd1esoUYxMUsB49G+H2EY95gHfeZwYhO2iZ7DpCvkEvAueeLjpbjFo/lau4LXLBdtm4/FpI6moQvcWtgZJllsmeBKqzoywKwucFjIuiIF4xdkMMlc78xumi+q6yOFHckKdUAWiCVoS3bHKMVpeowz58e6KdyUtHiIfTJasp4QKBAp+xrURe7psPS9BZViaNrwA/cWUwLtcebz0htIcHJmB3HONY=
  - secure: S3eQWvcQz18audXXCVZBdJ9SDhDP8L0uTQJKB+Dfl8fP7u0/IJNF/h0GJLTFPuf65LxrzXtpdpmP6/9Z+bjJNkm1PuUzHOKDnWBAte+T+LCEoDrMzK3Rt6+mITMmCBYABYwqU7yFfO4GkjwiM2Aaic25R1qQsMYEj6kqPWVn2K4mgy5PQMPPn59wycaP5QJeNQaXSoUOeOvO6RbrVgJyprPXBbaRAUfWfkKxEIO/U8UgDsuPNlRyHsCdLKYI1Lv2SGT+rZ1y5D/EaTC9z6MP2ftlZ75UU/K5W0QjQYKTrZTnovtCx6hV9oaMmyWSRCh3SHINYNLNJdo3IF7TyMSOZNnG1rMCVK1Et7PrbnLhY93ZUsI1gJdEsBrwHG58tY/sgtIw6elSCdgj9QbhJDp0INBbXxJM/VXsDM7pZCqhAc0R3BmtKH0nolTp0BSz10I+hdllmF3enDx7d49nuMy96hxhskbTK5SSiw/oFf9KNyC1l1MfqHEzlw150qqhL7TbJK64SBLaBYWUJVQeNUI8mEHLtx1h7RUkQsr81BduXfgJ5UJhx4mHNHCtS2IIyGeSVqffJcmVRiGjeAflyfksoiFCwF/RN+xK3k7KE/oXvd8mNbF3ulQ1WwJgaXDSnKRm1WNvPsZDwfxyidrgcou6SA1pE2E3T5wnzwsdVzidhps=
